#____       _   _            _____             _   _      _____
#|  _ \     | | | |          |  __ \           | | | |    / ____|
#| |_) | ___| |_| |_ ___ _ __| |  | | ___  __ _| |_| |__ | (___   ___ _ __ ___  ___ _ __
#|  _ < / _ \ __| __/ _ \ '__| |  | |/ _ \/ _` | __| '_ \ \___ \ / __| '__/ _ \/ _ \ '_ \
#| |_) |  __/ |_| ||  __/ |  | |__| |  __/ (_| | |_| | | |____) | (__| | |  __/  __/ | | |
#|____/ \___|\__|\__\___|_|  |_____/ \___|\__,_|\__|_| |_|_____/ \___|_|  \___|\___|_| |_|

#Author: Tedesk

#The config.yml was created with 1.8.8 in mind.
#Please check the Sounds for your server version!
misc: #Available languages: en-US, pt-BR, zh-TW
  language: 'en-US'
  use-safe-teleport: true
  use-default-world-spawn: true #If this option is enabled, the spawn section on locations.yml will be ignored.
  use-kill-camera: true #If this option is enabled, the player will spectate the killer.
sound: #sound;volume;pitch
  death:
    - BLAZE_DEATH;1.0;1.0
    - ANVIL_LAND;1.0;1.0
    - ITEM_PICKUP;1.0;1.0
    - ENDERMAN_DEATH;1.0;1.0
  countdown:
    - NOTE_BASS_DRUM;1.0;1.0
    - CLICK;1.0;1.0
  respawn:
    - NOTE_PLING;1.0;1.0
    - ORB_PICKUP;1.0;1.0
    - LEVEL_UP;1.0;1.0
  kill:
    - SKELETON_DEATH;1.0;1.0
    - GLASS;1.0;1.0
animation: #Available types: NONE, BLOOD, EXPLOSION, LIGHTNING (You can mix. Example: LIGHTNING-EXPLOSION)
  type: "BLOOD"
time:
  duration: 10
permissions:
  instant-respawn: 'bds.respawn'
  keep-xp: 'bds.xp'
  vip-spawn: 'bds.vip'
  admin: 'bds.admin'
spectator-settings:
  queue-teleport: true
  allow-spectate: false
  allow-teleport-with-keys: false
  ignore-walls: false
  allow-move: true
  allow-commands: false