#  ____       _   _            _____             _   _      _____
# |  _ \     | | | |          |  __ \           | | | |    / ____|
# | |_) | ___| |_| |_ ___ _ __| |  | | ___  __ _| |_| |__ | (___   ___ _ __ ___  ___ _ __
# |  _ < / _ \ __| __/ _ \ '__| |  | |/ _ \/ _` | __| '_ \ \___ \ / __| '__/ _ \/ _ \ '_ \
# | |_) |  __/ |_| ||  __/ |  | |__| |  __/ (_| | |_| | | |____) | (__| | |  __/  __/ | | |
# |____/ \___|\__|\__\___|_|  |_____/ \___|\__,_|\__|_| |_|_____/ \___|_|  \___|\___|_| |_|

# Author: Tedesk

misc: # Available languages: en-US, pt-BR
  language: "en-US"
  respawn-time: 10
  use-safe-teleport: true
commands-on-death:
# sender: command
# Variables: @player, @killer
# If killer is not a player or doesn't exist, the commands using it will be ignored.
# - "console: /i"
# - "player: /love" # Without the slash, the player will send a message in chat.
# - "killer: /you"
message-type:
  # Choose where the respective messages should appear.
  # Types: ACTIONBAR, TITLE, CHAT
  # Use \n to use subtitles.
  kill: "CHAT"
  killed: "TITLE"
  killed-by-player: "TITLE"
  countdown: "ACTIONBAR"
sound:
  # This section is compatible with resource pack sounds.
  # sound;volume;pitch
  death:
    - "ENTITY_BLAZE_DEATH;1.0;1.0"
    - "BLOCK_ANVIL_LAND;1.0;1.0"
    - "ENTITY_ITEM_PICKUP;1.0;1.0"
    - "ENTITY_ENDERMAN_DEATH;1.0;1.0"
  countdown:
    - "BLOCK_NOTE_BLOCK_BASEDRUM;1.0;1.0"
    - "UI_BUTTON_CLICK;1.0;1.0"
  respawn:
    - "BLOCK_NOTE_BLOCK_PLING;1.0;1.0"
    - "ENTITY_EXPERIENCE_ORB_PICKUP;1.0;1.0"
    - "ENTITY_PLAYER_LEVELUP;1.0;1.0"
  kill:
    - "ENTITY_SKELETON_DEATH;1.0;1.0"
    - "BLOCK_GLASS_BREAK;1.0;1.0"
animation:
  # Types: BLOOD, LIGHTNING, EXPLOSION, RANDOM (Use NONE to disable)
  type: "BLOOD"
permissions:
  instant-respawn: 'bds.instant-respawn'
  admin: 'bds.admin'
death-settings:
  queue-teleport: true
  allow-fly: true
  allow-spectate: true
  allowed-commands: # If you want to disable all commands, use []
    - "/g"
    - "/report"