name: BetterDeathScreen
main: com.github.victortedesco.bds.BetterDeathScreen
description: Plugin that offers a wide variety of options to customize the death screen of Minecraft.
version: ${project.version}
author: Tedesk
load: POSTWORLD
depend: [ ProtocolLib ]
softdepend: [ PlaceholderAPI ]
api-version: 1.13
website: https://www.spigotmc.org/resources/102005/

commands:
  bds:
    description: Main command of the plugin.
    usage: /<command>