name: BetterDeathScreen Build and Upload

on:
  push:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: github
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn package --file pom.xml

      - name: Upload Bukkit Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BetterDeathScreen-Bukkit
          path: bukkit/target/BetterDeathScreen.jar

      - name: Upload API Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BetterDeathScreen-API
          path: api/target/BetterDeathScreen-API.jar